### ISSUE TITLE
[BUG] [ws-bulk-report-generator] Issue Short Description

### ISSUE THREAD

**Issue by hvincentwss** [whitesource-ps/ws-bulk-report-generator#23]
**Bug Description**  
Timeout error when run on large orgs

**Steps to Reproduce**  
1. Run bulk report generator on org with > 1300 products (contact me for example)
2. Use the following command to run: python bulk_report_generator.py -u <redacted> -k <redacted> -r vulnerability -s product -a https://saas.whitesourcesoftware.com/

**Expected Behavior**  
Bulk generator runs successfully, returning all reports

**Actual Behavior**
Less than 400 out of 1300 reports were generated

**Environment Details**  
 - OS: Windows
 - Version 0.1.7

**Additional Context**  
Logs from failed run: 
ERROR:root:Error producing report
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Python39\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Python39\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Python39\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Python39\lib\http\client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "C:\Python39\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Python39\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

**Comment by hvincentwss** [comment]
[errors-whitesource.txt](https://github.com/whitesource-ps/ws-bulk-report-generator/files/7720096/errors-whitesource.txt)

**Comment by hvincentwss** [comment]
See the following error as well : 

INFO:root:Found 1357 tokens to generate reports
Traceback (most recent call last):
File "/Users/hurtadg/ADSK/projects/harmony_pyenv/bin/ws_bulk_report_generator", line 8, in <module>
sys.exit(main())
File "/Users/hurtadg/ADSK/projects/harmony_pyenv/lib/python3.7/site-packages/ws_bulk_report_generator/bulk_report_generator.py", line 156, in main
generate_reports_manager(report_scopes)
File "/Users/hurtadg/ADSK/projects/harmony_pyenv/lib/python3.7/site-packages/ws_bulk_report_generator/bulk_report_generator.py", line 136, in generate_reports_manager
pool.starmap(worker_generate_report, [(report_desc, ws_conn) for report_desc in reports_desc_list])
File "/Users/hurtadg/.pyenv/versions/3.7.3/lib/python3.7/multiprocessing/pool.py", line 276, in starmap
return self._map_async(func, iterable, starmapstar, chunksize).get()
File "/Users/hurtadg/.pyenv/versions/3.7.3/lib/python3.7/multiprocessing/pool.py", line 657, in get
raise self._value
File "/Users/hurtadg/.pyenv/versions/3.7.3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
result = (True, func(*args, **kwds))
File "/Users/hurtadg/.pyenv/versions/3.7.3/lib/python3.7/multiprocessing/pool.py", line 47, in starmapstar
return list(itertools.starmap(args[0], args[1]))
File "/Users/hurtadg/ADSK/projects/harmony_pyenv/lib/python3.7/site-packages/ws_bulk_report_generator/bulk_report_generator.py", line 142, in worker_generate_report
output = args.report_method(ws_connector, token=report_desc['token'], report=args.is_binary)
File "/Users/hurtadg/ADSK/projects/harmony_pyenv/lib/python3.7/site-packages/ws_sdk/web.py", line 28, in wrapper
return function.__call__(*args, **kwargs)
File "/Users/hurtadg/ADSK/projects/harmony_pyenv/lib/python3.7/site-packages/ws_sdk/web.py", line 691, in get_vulnerability
ret = self.__generic_get__(get_type='VulnerabilityReport', token_type=token_type, kv_dict=kv_dict)
File "/Users/hurtadg/ADSK/projects/harmony_pyenv/lib/python3.7/site-packages/ws_sdk/web.py", line 240, in __generic_get__
return self.call_ws_api(request_type=f"get{token_type.capitalize()}{get_type}", kv_dict=kv_dict)
File "/Users/hurtadg/ADSK/projects/harmony_pyenv/lib/python3.7/site-packages/ws_sdk/web.py", line 204, in call_ws_api
logger.error(f"API {body['requestType']} call on {body[token[-1]]} failed: {resp.text}")
KeyError: 'n'
%
