### ISSUE TITLE
[BUG] [ws-bulk-report-generator] Bulk Report Fails due to Disabled Orgs

### ISSUE THREAD

**Issue by jbnable** [whitesource-ps/ws-bulk-report-generator#45]
**Bug Description**  
Bulk report fails. I removed all the data that might be sensitive (paths, tokens), the rest is below.

**Steps to Reproduce**  
python bulk_report_generator.py -a https://app.whitesourcesoftware.com -u * -k * -y globalOrganization -o Bulk -r inventory -t unified_json -x lib_name="tdigest-0.1.1.tgz"
INFO 2022-02-03 12:31:50,990 20124 bulk_report_generator: Start running WS Bulk Report Generator Version 0.2.1 on token *. Parallelism level: 10
INFO 2022-02-03 12:31:51,806 20124 bulk_report_generator: Found: 22 Organizations under Global Organization token: *
WARNING 2022-02-03 12:31:52,432 20188 bulk_report_generator: Organization: 'xyz' is disabled and will be skipped
Traceback (most recent call last):
  File "C:\\\\\ws-bulk-report-generator\ws_bulk_report_generator\bulk_report_generator.py", line 287, in <module>
    main()
  File "C:\\\\\ws-bulk-report-generator\ws_bulk_report_generator\bulk_report_generator.py", line 277, in main
    report_scopes = get_reports_scopes()
  File "C:\\\\\ws-bulk-report-generator\ws_bulk_report_generator\bulk_report_generator.py", line 112, in get_reports_scopes   
    scopes, errors = generic_thread_pool_m(orgs, get_reports_scopes_from_org_w)
  File "C:\\\\\ws-bulk-report-generator\ws_bulk_report_generator\bulk_report_generator.py", line 133, in generic_thread_pool_m
    logger.error(f"Error on future: {future.result()}")
  File "C:\Users\****\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Users\****\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\\\\\ws-bulk-report-generator\ws_bulk_report_generator\bulk_report_generator.py", line 128, in generic_thread_pool_m
    temp_l = future.result()
  File "C:\Users\****\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Users\****\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Users\****\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\\\\\ws-bulk-report-generator\ws_bulk_report_generator\bulk_report_generator.py", line 175, in get_reports_scopes_from_org_w
    prep_scope(scopes)
UnboundLocalError: local variable 'scopes' referenced before assignment

**Expected Behavior**  
Bulk report is generated.

**Screenshots**  

**Environment Details**  
 - OS: Windows 10

**Additional Context**

**Comment by jbnable** [comment]
The error is related to disabled orgs.

**Comment by rammatzkvosky** [comment]
Hi @jbnable , I'm working to fix this issue and will get back to you in advance.

**Comment by rammatzkvosky** [comment]
Hi @jbnable - we released a new version with a fix.
Please check https://pypi.org/project/ws-bulk-report-generator/0.2.2/

Also , why did you run the tool from the cloned repo and not installed from pypi ( see [README.md](https://github.com/whitesource-ps/ws-bulk-report-generator/blob/master/README.md#installation-and-execution-by-pulling-package-from-pypi) )

**Comment by jbnable** [comment]
I ran it both ways, got the same error running it in linux after installing with pip. I was messing with the code so it was easier to clone the repo.

**Comment by rammatzkvosky** [comment]
Thanks for the update @jbnable .
Were you able to run the [latest version](https://pypi.org/project/ws-bulk-report-generator/0.2.2/) successfully ?
Can I close this issue ?

**Comment by jbnable** [comment]
I was able to run it with the disabled org removed from the global org, so I can't test whether this works unless I disable another org. I may do that in the future, thanks again.
