### ISSUE TITLE
[BUG] [ws-bulk-report-generator] Bulk Reporter Errors Out

### ISSUE THREAD

**Issue by jbnable** [whitesource-ps/ws-bulk-report-generator#50]
**Bug Description**  
Vulnerability bulk report fails with error below, after running through 100s of repos.

**Steps to Reproduce**  
python bulk_report_generator.py -a https://app.whitesourcesoftware.com -u <user token> -k <Global Org Token> -y globalOrganization -o Bulk -r vulnerability -t unified_xlsx

**Expected Behavior**  
Report is generated.

**Screenshots**  
INFO 2022-02-07 20:06:05,503 25692 bulk_report_generator: Running 'vulnerability' report on product: 'xyz'
INFO 2022-02-07 20:06:05,613 8400 bulk_report_generator: Running 'vulnerability' report on product: 'xyz2'
Traceback (most recent call last):
  File "\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\response.py", line 697, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\response.py", line 438, in _error_catcher
    yield
  File "\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\response.py", line 764, in read_chunked
    self._update_chunk_length()
  File "\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\response.py", line 701, in _update_chunk_length
    raise InvalidChunkLength(self, line)
urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 760, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\response.py", line 572, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\response.py", line 752, in read_chunked
    with self._error_catcher():
  File "\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\response.py", line 455, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ws-bulk-report-generator\ws_bulk_report_generator\bulk_report_generator.py", line 287, in <module>
    main()
  File "ws-bulk-report-generator\ws_bulk_report_generator\bulk_report_generator.py", line 278, in main
    ret, errors = generate_reports(report_scopes)
  File "ws-bulk-report-generator\ws_bulk_report_generator\bulk_report_generator.py", line 261, in generate_reports
    return generic_thread_pool_m(ent_l=report_scopes, worker=generate_report_w)
  File "ws-bulk-report-generator\ws_bulk_report_generator\bulk_report_generator.py", line 133, in generic_thread_pool_m
    logger.error(f"Error on future: {future.result()}")
  File "\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "ws-bulk-report-generator\ws_bulk_report_generator\bulk_report_generator.py", line 128, in generic_thread_pool_m
    temp_l = future.result()
  File "\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "ws-bulk-report-generator\ws_bulk_report_generator\bulk_report_generator.py", line 184, in generate_report_w
    output = args.report_method(report_desc['ws_conn'],
  File "\AppData\Local\Programs\Python\Python310\lib\site-packages\ws_sdk\web.py", line 29, in wrapper
    return function.__call__(*args, **kwargs)
  File "\AppData\Local\Programs\Python\Python310\lib\site-packages\ws_sdk\web.py", line 824, in get_vulnerability
    ret = self._generic_get(get_type='VulnerabilityReport', token_type=token_type, kv_dict=kv_dict)
  File "\AppData\Local\Programs\Python\Python310\lib\site-packages\ws_sdk\web.py", line 259, in _generic_get
    return self.call_ws_api(request_type=f"get{token_type.capitalize()}{get_type}", kv_dict=kv_dict)
  File "\AppData\Local\Programs\Python\Python310\lib\site-packages\ws_sdk\web.py", line 211, in call_ws_api
    resp = self.session.post(url=self.api_url, data=json.dumps(body), headers=self.headers, timeout=self.timeout)
  File "\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 577, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 687, in send
    r.content
  File "\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 838, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 763, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

**Environment Details**  
 - OS: Windows 10
 - Python 3.10.2 64-bit

**Additional Context**

**Comment by rammatzkvosky** [comment]
Hi @jbnable - could you please share the organization name ?
It will assist me to reproduce this issue.

You can also share these details and full logs by addressing [support@whitesourcesoftware.com](support@whitesourcesoftware.com)

**Comment by rammatzkvosky** [comment]
Hi @jbnable  , kindly share the Whitesource org name which the xyz product belongs to.

**Comment by jbnable** [comment]
I didn't keep a record, and I don't want to post it publicly. Feel free to close this if you can't solve the bug without it.

Thanks
