### ISSUE TITLE
[BUG] [ws-bulk-report-generator] Unable to run reports on organization

### ISSUE THREAD

**Issue by bjohnson225** [whitesource-ps/ws-bulk-report-generator#58]
**Bug Description**  
Hi, I am unable to run the bulk report generator and was asked to create an issue here. If I run the ws_bulk_report_generator script then it will return an error which says “User token: '...' has insufficient permissions”. The token it prints out here in place of the ellipses is actually the organization key, so the error message may be misleading. 

This is using a user token I created myself in the WhiteSource UI and the API key for the organization taken from the Integrate tab. 

**Steps to Reproduce**  
1. run (with the appropriate keys) `ws_bulk_report_generator -u <user key> -k <organization api key> -s project -r due_diligence -t json` from the terminal. 

The same applies for all other example scripts which I took from the Readme.

**Console Output**  
```
INFO 2022-04-01 14:16:20,197 4521850368 bulk_report_generator: Start running WS Bulk Report Generator Version 0.2.3 on token <organization key>. Parallelism level: 10
Traceback (most recent call last):
  File "/usr/local/bin/ws_bulk_report_generator", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/ws_bulk_report_generator/bulk_report_generator.py", line 274, in main
    report_scopes = get_reports_scopes()
  File "/usr/local/lib/python3.9/site-packages/ws_bulk_report_generator/bulk_report_generator.py", line 112, in get_reports_scopes
    orgs = [args.ws_conn.get_organization_details()]
  File "/usr/local/lib/python3.9/site-packages/ws_sdk/app.py", line 51, in wrapper
    return function.__call__(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/ws_sdk/app.py", line 657, in get_organization_details
    org_details = self._generic_get(get_type='Details')
  File "/usr/local/lib/python3.9/site-packages/ws_sdk/app.py", line 264, in _generic_get
    return self.call_ws_api(request_type=f"get{token_type.capitalize()}{get_type}", kv_dict=kv_dict)
  File "/usr/local/lib/python3.9/site-packages/ws_sdk/app.py", line 232, in call_ws_api
    __handle_ws_server_errors(resp.text)
  File "/usr/local/lib/python3.9/site-packages/ws_sdk/app.py", line 196, in __handle_ws_server_errors
    raise WsSdkServerInsufficientPermissions(body[token])
ws_sdk.ws_errors.WsSdkServerInsufficientPermissions: User token: '<organization key>' has insufficient permissions
```

**Environment Details**  
 - zsh on MacOS Monterey 12.2.1

**Comment by NatalyaDalid** [comment]
Hello @bjohnson225 ,

Could you please double-check your <user key>? There are two options to get this key:
1. generate this in the Profile -> User Keys section.
2. generate a service user (including the token) with Admin permissions in the Admin -> Users area. 

Please let us know if it helps.

Thanks,
WhiteSource PS Team

**Comment by bjohnson225** [comment]
ok, thanks for the help @NatalyaDalid. I'll close this issue as we've got the script working now.
