### ISSUE TITLE
[BUG] [ws-bulk-report-generator] Issue Short Description

### ISSUE THREAD

**Issue by joshconkel** [whitesource-ps/ws-bulk-report-generator#61]
**Bug Description**  
We are trying to run the bulk report generator against all of the projects in our organization with WhiteSource. The program crashes if we use the API key for one org., but works fin with the second org. The one that crashes had a shorter API key that uses dashes.

**Steps to Reproduce**  

Run report with an API key that uses dashes:

ws_bulk_report_generator -a https://saas.whitesourcesoftware.com -u 888XXXXXXXXXXXXXXX888 -k 3xxxxxxx3-xxxx-xxxx-xxxx-8xxxxxxxxx8 -s product -r vulnerability -t json -o /tmp/

**Expected Behavior**  
I expected the report to run without crashing. It runs successfully if we use the other org. API key without dashes.

**Screenshots**  

INFO 2022-05-09 23:09:26,975 139997118183232 bulk_report_generator: Start running WS Bulk Report Generator Version 0.2.4 on token 3xxxxxxx3-xxxx-xxxx-xxxx-8xxxxxxxxx8. Parallelism level: 10
Traceback (most recent call last):
  File "/usr/local/bin/ws_bulk_report_generator", line 8, in <module> sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/ws_bulk_report_generator/bulk_report_generator.py", line 283, in main
    report_scopes = get_reports_scopes()
  File "/usr/local/lib/python3.8/site-packages/ws_bulk_report_generator/bulk_report_generator.py", line 113, in get_reports_scopes
    scopes, errors = generic_thread_pool_m(orgs, get_reports_scopes_from_org_w)
  File "/usr/local/lib/python3.8/site-packages/ws_bulk_report_generator/bulk_report_generator.py", line 136, in generic_thread_pool_m
    logger.error(f"Error on future: {future.result()}")
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/site-packages/ws_bulk_report_generator/bulk_report_generator.py", line 131, in generic_thread_pool_m
    temp_l = future.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/ws_bulk_report_generator/bulk_report_generator.py", line 167, in get_reports_scopes_from_org_w
    org_conn.token = org['orgToken']
KeyError: 'orgToken'

**Environment Details**  
 - OS: Centos 8 stream
 - Browser: Edge, N/A
 - Versions:
            Package                  Version
       ------------------------ ---------
       certifi                  2021.10.8
       charset-normalizer       2.0.12
       DateTime                 4.4
       idna                     3.3
       pip                      22.0.4
       pytz                     2022.1
       requests                 2.27.1
       setuptools               41.2.0
       urllib3                  1.26.9
       ws-bulk-report-generator 0.2.4
       ws-sdk                   0.9a3
       XlsxWriter               3.0.3
       zope.interface           5.4.0

Python 3.8.1

**Comment by NatalyaDalid** [comment]
Hello @joshconkel ,

Could you also please share your Company name (here or by email ps@whitesourcesoftware.com)

Thanks, 
WS PS Team

**Comment by NatalyaDalid** [comment]
Thank you @joshconkel for the provided detail, 

The bug has been reproduced and will be fixed soon. 

Thank you for this finding!
WS PS Team

**Comment by NatalyaDalid** [comment]
Hi @joshconkel,

Please try the latest version v0.3.0.

Thanks,
Natalya

**Comment by joshconkel** [comment]
I'm now getting this error. Do I need to escape the key somehow?

ws_sdk.ws_errors.WsSdkServerGenericError: Generic error on token: 'None'. Error: {"errorCode":1002,"errorMessage":"Invalid organization token"}

**Comment by joshconkel** [comment]
The update has been working well, I had to specify the version number when upgrading the pip module.

This can be closed if it passes all internal tests as well. Thank you!
